import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateAttendancePDF = (session, participants) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text('Sparkus - Attendance Report', 14, 20);

    // Session Details
    doc.setFontSize(12);
    doc.text(`Session: ${session.session_name}`, 14, 30);
    doc.text(`Code: ${session.session_code}`, 14, 36);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 42);
    doc.text(`Total Participants: ${participants.length}`, 14, 48);

    // Table
    const tableColumn = ["Roll Number", "Name", "Focus Score", "Status", "Joined At"];
    const tableRows = participants.map(p => [
        p.roll_number,
        p.full_name,
        `${p.final_focus_score}%`,
        p.attendance_status || (parseFloat(p.final_focus_score) > 40 ? 'Present' : 'Absent'),
        new Date(p.joined_at).toLocaleString()
    ]);

    doc.autoTable({
        head: [tableColumn],
        body: tableRows,
        startY: 55,
        theme: 'grid',
        styles: { fontSize: 10 },
        headStyles: { fillColor: [79, 70, 229] } // Indigo-600
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.text(`Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);
        doc.text('Generated by Sparkus', doc.internal.pageSize.width - 50, doc.internal.pageSize.height - 10);
    }

    return doc.output('arraybuffer');
};

export const generateExamReportPDF = (session, participants, violations) => {
    // Similar structure but with violations table
    // Placeholder implementation
    return generateAttendancePDF(session, participants);
};
